github.com:
    users:
        AceTheDactyl:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: AceTheDactyl
