name: Living Library CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn[standard]

      - name: Static checks (placeholder)
        run: python -m compileall library_core
