name: Release on Tag

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi

      - name: Run unit tests
        run: python -m pytest -q

      - name: Run Kira integrity tests
        run: python3 vesselos.py kira test

      - name: Generate release documentation
        run: python3 scripts/generate_release_docs.py --tag "${{ github.ref_name }}" --types

      - name: Configure git author (for packaging metadata)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Publish release (Kira)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 vesselos.py kira publish --run --release --tag "${{ github.ref_name }}" \
            --notes-file dist/RELEASE_NOTES.md \
            --asset docs/kira_knowledge.md \
            --asset dist/RELEASE_NOTES.md \
            --asset tools/codex-cli/types/knowledge.d.ts
