name: CI

on:
  push:
    branches: ["**"]
    tags: ["v*.*.*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies (if any)
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          else
            echo "No requirements.txt found; skipping Python deps."
          fi

      - name: Python CLI smoke test
        run: |
          python scripts/codex_cli.py --help || true

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Node CLI smoke test
        run: |
          node -v
          node cli.js "CI ping" -c '{"who":"CI"}' || true

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create bundles
        run: |
          mkdir -p dist
          zip -r dist/codex_tools.zip \
            scripts/codex_cli.py \
            scripts/codex \
            scripts/codex-wizard \
            scripts/export_wizard.py \
            codex/core \
            codex/config.yaml \
            cli.js || true
          ls -al dist

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
